// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qYybH3l6_N0kOyCYCdG5HRxoKnDUpZY',
    appId: '1:52476982233:web:898d4de772ea7fcb7c5fc8',
    messagingSenderId: '52476982233',
    projectId: 'liceth-28',
    authDomain: 'liceth-28.firebaseapp.com',
    storageBucket: 'liceth-28.appspot.com',
    measurementId: 'G-NHJ29KJ7ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBih-XMJfgAD6x8YjHoOyCmEPWAZ9Yz-Wc',
    appId: '1:52476982233:android:93d917250d7edfdb7c5fc8',
    messagingSenderId: '52476982233',
    projectId: 'liceth-28',
    storageBucket: 'liceth-28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColTK1iz09MNEq2mxUxIH219EKjTDJJtg',
    appId: '1:52476982233:ios:e6a7889026d755547c5fc8',
    messagingSenderId: '52476982233',
    projectId: 'liceth-28',
    storageBucket: 'liceth-28.appspot.com',
    androidClientId: '52476982233-3td6fq2pkovgtcu15kdalvtqgua283ga.apps.googleusercontent.com',
    iosClientId: '52476982233-ihtqs8s8d845s9loabdq33eb21baiv65.apps.googleusercontent.com',
    iosBundleId: 'com.example.licethApp',
  );
}
